# Generated by Django 4.0 on 2022-01-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('park', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='내용')),
                ('score', models.IntegerField(verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초작성날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='최근수정날짜')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('park_id', models.ForeignKey(db_column='park_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_park', to='park.park', verbose_name='공원ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='user.user', verbose_name='유저ID')),
            ],
        ),
    ]
