FROM node:16.13-alpine

WORKDIR /srv/client/

# node... path에 추가
ENV PATH /srv/client/node_modules/.bin:$PATH

# 의존성 설치
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add app
COPY . ./

# react 빌드
RUN npm run build