# Generated by Django 4.0 on 2022-01-03 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="운동기구 이름"
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(max_length=50, verbose_name="운동기구 유형"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "park_name",
                    models.CharField(max_length=50, unique=True, verbose_name="공원이름"),
                ),
                ("gu_id", models.IntegerField(verbose_name="구ID")),
                ("full_address", models.TextField(verbose_name="주소")),
                ("si_address", models.CharField(max_length=50, verbose_name="시")),
                ("gu_address", models.CharField(max_length=50, verbose_name="구")),
                ("dong_address", models.CharField(max_length=50, verbose_name="동")),
                ("latitude", models.CharField(max_length=50, verbose_name="위도(lat)")),
                ("longitude", models.CharField(max_length=50, verbose_name="경도(long)")),
                (
                    "park_image",
                    models.ImageField(blank=True, upload_to="", verbose_name="공원사진"),
                ),
            ],
            options={
                "ordering": ["park_name"],
            },
        ),
        migrations.CreateModel(
            name="ParkEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="수량")),
            ],
            options={
                "ordering": ["park_id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="생성된 날짜",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 날짜"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                ("deleted_at", models.DateTimeField(null=True, verbose_name="삭제된 날짜")),
                ("content", models.CharField(max_length=255, verbose_name="내용")),
                ("score", models.IntegerField(verbose_name="평점")),
                (
                    "park_id",
                    models.ForeignKey(
                        db_column="park_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_park",
                        to="park.park",
                        verbose_name="공원 ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
