# Generated by Django 4.0 on 2022-01-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=50, unique=True, verbose_name='운동기구 이름')),
                ('equipment_type', models.CharField(max_length=50, verbose_name='운동기구 유형')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=50, unique=True, verbose_name='공원이름')),
                ('gu_id', models.IntegerField(verbose_name='구ID')),
                ('full_address', models.TextField(verbose_name='주소')),
                ('si_address', models.CharField(max_length=50, verbose_name='시')),
                ('gu_address', models.CharField(max_length=50, verbose_name='구')),
                ('dong_address', models.CharField(max_length=50, verbose_name='동')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='위도(lat)')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='경도(long)')),
                ('park_image', models.ImageField(blank=True, upload_to='', verbose_name='공원사진')),
            ],
            options={
                'ordering': ['park_name'],
            },
        ),
        migrations.CreateModel(
            name='ParkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('equipment_id', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='park.equipment', verbose_name='운동시설ID')),
                ('park_id', models.ForeignKey(db_column='park_id', on_delete=django.db.models.deletion.CASCADE, related_name='park', to='park.park', verbose_name='공원ID')),
            ],
            options={
                'ordering': ['park_id'],
            },
        ),
    ]
