# Generated by Django 4.0 on 2021-12-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("park_name", models.CharField(max_length=50)),
                ("gu_id", models.IntegerField()),
                ("full_address", models.TextField()),
                ("si_address", models.CharField(max_length=50)),
                ("gu_address", models.CharField(max_length=50)),
                ("dong_address", models.CharField(max_length=50)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="위도(lat)"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=11, verbose_name="경도(long)"
                    ),
                ),
                ("park_image", models.ImageField(blank=True, upload_to="")),
            ],
            options={
                "ordering": ["park_name"],
            },
        ),
    ]


# flake8: noqa
