# Generated by Django 4.0 on 2021-12-29 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=50)),
                ('equipment_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, to='park.equipment')),
                ('park_id', models.ForeignKey(db_column='park_id', on_delete=django.db.models.deletion.CASCADE, to='park.park')),
            ],
            options={
                'ordering': ['park_id'],
            },
        ),
    ]
