# Generated by Django 4.0 on 2022-01-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkequipment',
            name='equipment_id',
            field=models.ForeignKey(db_column='equipment_parks', on_delete=django.db.models.deletion.CASCADE, related_name='park', to='park.equipment', verbose_name='운동시설 ID'),
        ),
        migrations.AlterField(
            model_name='parkequipment',
            name='park_id',
            field=models.ForeignKey(db_column='park_id', on_delete=django.db.models.deletion.CASCADE, related_name='park_equipments', to='park.park', verbose_name='공원 ID'),
        ),
    ]
