# Generated by Django 4.0 on 2022-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_alter_parkequipment_equipment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='nearby_parks',
            field=models.ManyToManyField(to='park.Park'),
        ),
        migrations.AlterField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제된 날짜'),
        ),
    ]
